os: linux
dist: xenial
language: python
env: TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.8
    - python: 3.8
      env: TOXENV=lowest
    - python: 3.7
    - python: 3.6
    - python: pypy3
    - python: 3.8
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master
    - /^\d+(\.\d+)*(\.x)?$/

notifications:
  email: false
