name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.8', python: '3.8', tox: py38}
          - {name: '3.7', python: '3.7', tox: py37}
          - {name: 'PyPy 3.9', python: 'pypy3.9', tox: pypy39}
          - {name: 'Typing', python: '3.10', os: ubuntu-latest, tox: typing}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: |
          pip install pdm "importlib-metadata<5"
          pdm sync -dG tox
      - run: pdm run tox -e ${{ matrix.tox }}
